### ISSUE TITLE
NFT are not showing on the staking UI.

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/hopr-devrel#85]
## Expected Behavior

On the staking UI, connecting wallet on xDai chain it should reflect all NFT's which are on your wallet address.

## Current Behavior

It doesn't show any NFT's.

## Steps to Reproduce

1. Connect wallet on xDai chain (make sure you have NFT's on that address)

## Screenshot

![image](https://user-images.githubusercontent.com/73285987/140080134-c3373426-8855-4e80-8fd0-03a770d70c4f.png)

## Console logs

![image](https://user-images.githubusercontent.com/73285987/140082953-bf78d5dd-2e3d-4fa3-aca3-fae46257975c.png)

![image](https://user-images.githubusercontent.com/73285987/140083022-b659768d-eae8-4c08-ad77-fd4f42c44d76.png)

**Comment by jjperezaguinaga** [comment]
@tolbrino @nionis The problem is that despite these tokens being minted (see `batchMint` [transaction](https://blockscout.com/xdai/mainnet/tx/0x0f6aab66dd791a845fcf3a8dcf7e19d9447295ed1baa88fb3bc0a3de5f67ecd2)), these images were not uploaded to our server (https://github.com/hoprnet/hopr-devrel/tree/main/stake/packages/frontend/public), as shown in https://github.com/hoprnet/hopr-community/issues/122. The only missing task is the upload of the assets to ipfs via IPFSPinata and then upload the metadata to our server (see https://github.com/hoprnet/hopr-community/issues/124 as an example).

I suggest that we put an outline on how to do this from scratch, especially with the IPFSPinata account, since AFAIK we don't have a company one. So the next steps would be to do the missing task, then create the documentation, and add an extra one to migrate the current NFT art from the current account (mine) to a company-owned one. In total, these three tasks should take approx. an hour, max two.

**Comment by tolbrino** [comment]
Sounds reasonable to me. Adding it to our taskboard.

**Comment by tolbrino** [comment]
cc @nionis

**Comment by Jaguaras** [comment]
Closing issue, it was solved.
